In [3]:
import numpy as np

In [1]:
rows, cols = (7, 7)
ar = []


In [6]:
lista = np.arange(1,65,1)
lista = lista.reshape(8,8)

In [8]:
listb= lista
lista



array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [19]:
listb = lista.transpose()

In [54]:
lista

array([[ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64]])

In [56]:
#i are columns, j are rows ins case of array[i,j]

for i in range (8)  :
    for j in range (8) :
        listb = str(lista[i][j])
        encontrar = listb.find('3')
        if(encontrar != -1):
            lista[i][j] = -99
        
        
        
        
        
        
        


In [57]:
lista

array([[  1,   9,  17,  25, -99,  41,  49,  57],
       [  2,  10,  18,  26, -99,  42,  50,  58],
       [-99,  11,  19,  27, -99, -99,  51,  59],
       [  4,  12,  20,  28, -99,  44,  52,  60],
       [  5, -99,  21,  29, -99,  45, -99,  61],
       [  6,  14,  22, -99, -99,  46,  54,  62],
       [  7,  15, -99, -99, -99,  47,  55, -99],
       [  8,  16,  24, -99,  40,  48,  56,  64]])

'[ 2 10 18 26 34 42 50 58]'

In [58]:
#Ejercicio 3

In [61]:
#parte 1
Matriz = np.arange(0.4,0.8,0.01)
Matriz

array([0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ,
       0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61,
       0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72,
       0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79])

In [63]:
Matriz = np.reshape (Matriz,(8,5))

In [64]:
Matriz

array([[0.4 , 0.41, 0.42, 0.43, 0.44],
       [0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54],
       [0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64],
       [0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74],
       [0.75, 0.76, 0.77, 0.78, 0.79]])

In [66]:
#Parte 2
lista

array([[  1,   9,  17,  25, -99,  41,  49,  57],
       [  2,  10,  18,  26, -99,  42,  50,  58],
       [-99,  11,  19,  27, -99, -99,  51,  59],
       [  4,  12,  20,  28, -99,  44,  52,  60],
       [  5, -99,  21,  29, -99,  45, -99,  61],
       [  6,  14,  22, -99, -99,  46,  54,  62],
       [  7,  15, -99, -99, -99,  47,  55, -99],
       [  8,  16,  24, -99,  40,  48,  56,  64]])

In [67]:
matriza = np.append(Matriz, lista, axis= 1)

In [68]:
matriza

array([[  0.4 ,   0.41,   0.42,   0.43,   0.44,   1.  ,   9.  ,  17.  ,
         25.  , -99.  ,  41.  ,  49.  ,  57.  ],
       [  0.45,   0.46,   0.47,   0.48,   0.49,   2.  ,  10.  ,  18.  ,
         26.  , -99.  ,  42.  ,  50.  ,  58.  ],
       [  0.5 ,   0.51,   0.52,   0.53,   0.54, -99.  ,  11.  ,  19.  ,
         27.  , -99.  , -99.  ,  51.  ,  59.  ],
       [  0.55,   0.56,   0.57,   0.58,   0.59,   4.  ,  12.  ,  20.  ,
         28.  , -99.  ,  44.  ,  52.  ,  60.  ],
       [  0.6 ,   0.61,   0.62,   0.63,   0.64,   5.  , -99.  ,  21.  ,
         29.  , -99.  ,  45.  , -99.  ,  61.  ],
       [  0.65,   0.66,   0.67,   0.68,   0.69,   6.  ,  14.  ,  22.  ,
        -99.  , -99.  ,  46.  ,  54.  ,  62.  ],
       [  0.7 ,   0.71,   0.72,   0.73,   0.74,   7.  ,  15.  , -99.  ,
        -99.  , -99.  ,  47.  ,  55.  , -99.  ],
       [  0.75,   0.76,   0.77,   0.78,   0.79,   8.  ,  16.  ,  24.  ,
        -99.  ,  40.  ,  48.  ,  56.  ,  64.  ]])

In [70]:
#Parte 3

m = np.array([])
for i in range (13):
    M = np.mean(matriza[:,i])
    m = np.append(m,M)

In [72]:
m

array([  0.575,   0.585,   0.595,   0.605,   0.615,  -8.25 ,  -1.5  ,
         5.25 , -20.25 , -81.625,  26.75 ,  33.5  ,  40.25 ])

In [73]:
matriza2=np.vstack([matriza,m])

In [74]:
matriza2

array([[  0.4  ,   0.41 ,   0.42 ,   0.43 ,   0.44 ,   1.   ,   9.   ,
         17.   ,  25.   , -99.   ,  41.   ,  49.   ,  57.   ],
       [  0.45 ,   0.46 ,   0.47 ,   0.48 ,   0.49 ,   2.   ,  10.   ,
         18.   ,  26.   , -99.   ,  42.   ,  50.   ,  58.   ],
       [  0.5  ,   0.51 ,   0.52 ,   0.53 ,   0.54 , -99.   ,  11.   ,
         19.   ,  27.   , -99.   , -99.   ,  51.   ,  59.   ],
       [  0.55 ,   0.56 ,   0.57 ,   0.58 ,   0.59 ,   4.   ,  12.   ,
         20.   ,  28.   , -99.   ,  44.   ,  52.   ,  60.   ],
       [  0.6  ,   0.61 ,   0.62 ,   0.63 ,   0.64 ,   5.   , -99.   ,
         21.   ,  29.   , -99.   ,  45.   , -99.   ,  61.   ],
       [  0.65 ,   0.66 ,   0.67 ,   0.68 ,   0.69 ,   6.   ,  14.   ,
         22.   , -99.   , -99.   ,  46.   ,  54.   ,  62.   ],
       [  0.7  ,   0.71 ,   0.72 ,   0.73 ,   0.74 ,   7.   ,  15.   ,
        -99.   , -99.   , -99.   ,  47.   ,  55.   , -99.   ],
       [  0.75 ,   0.76 ,   0.77 ,   0.78 ,   0.79 ,   8.   , 

In [78]:
s = np.array([])
for i in range(9):
    maxi = max(matriza2[i, :])
    s = np.append(s,maxi)

In [79]:
s.transpose()

array([57.  , 58.  , 59.  , 60.  , 61.  , 62.  , 55.  , 64.  , 40.25])

In [ ]:
matriz3=np.append(matriza2, np.array)